Timberland final v3
timberland-sig/dracut pull request #6
Opened 2023-04-07 07:07 UTC by johnmeneghini

These are the patches I'm using in the rh-linux-poc.

Note the most recent patch, which enables everything to work with @stuarthayes latest nvme-cli changes.

## Changes

## Checklist
- [ x] I have tested it locally
- [ ] I have reviewed and updated any documentation if relevant
- [ x] I am providing new code and test(s) for it

Fixes #

2023-04-18 09:17 UTC, mwilck requested changes
This must be merged with #5. Also, the `connect-all` logic must be discussed.

With the merge of the nvme-cli code, the situation is different than before. We now have the `connect-all` command that supports both NBFT and ordinary discovery. Thus we could simplify the dracut logic substantially by simply running `nvme connect-all`, without distinguishing the various cases (NBFT present, `discovery.conf` present, `config.json` present, etc.) as `connect-all` carries out the same tests again.

This comes down to the discussion I had previously with @hreinecke, who argued that we should simply use `connect-all`, always, whereas I think that for the purpose of activating the root file system, it makes sense to limit ourselves to those subsystems/namespaces that are actually necessary. At least, it should be **possible** for the admin to enforce such a limitation (e.g. if either the NBFT or the static `discovery.conf` contains broken data, which might lead to timeouts or even a wrong root file system mounted).

We have `rd.nvmf.nonbft` already and we need to keep supporting that.
IMO that would imply that we must call `connect-all --no-nbft` if this parameter is given.

Likewise, IMO we would need `rd.nvmf.nbft` or `rd.nbft.nbftonly` if we want to allow the admin to force use of **only** NBFT provided subsystems. This would require calling `nvme connect-all --nbft`.

Now we have the problem that all versions of `nvme` except the latest will error out with these command line options. So we need to  implement a fallback.

Wrt static discovery (`discovery.conf`, `config.json`), we must also keep in mind that TCP and RDMA connection attempts to non-reachable network destinations might fail or worse, time out, unless dracut has been configured to bring up the network. Only NBFT configuration basically ensures that with every configured subsystems comes a matching HFI entry, and that these subsystems will probably be reachable.

AFAICS, we have two options now:

1. Just use `connect-all`, as suggested by @hreinecke, and don't bother about using NBFT or local configuration. That would simplify the dracut code substantially, and it would (sort of) minimize the risk that the root FS isn't found we donn't connect to the subsystem that contains it. It suffers from the issues mentioned above though.

2. Fix the existing logic to handle the various cases mentioned above.

Not surprisingly, I vote for 2. I'd like to base our upstream dracut PR on 2.), and have a discussion about the `connect-all` logic in the upstream PR. If upstream comes to the conclusion that the complexity of differentiating the various cases is unnecessary, we can still simplify the PR.

2023-04-20 16:16 UTC, johnmeneghini commented on modules.d/95nvmf/nvmf-autoconnect.sh
> +    /usr/sbin/nvme connect-all
No, the upstream change code does not require this.  This patch is from @charles-rose

2023-04-21 14:56 UTC, johnmeneghini commented on modules.d/95nvmf/nvmf-autoconnect.sh
> +    /usr/sbin/nvme connect-all
fixed

2023-04-21 14:57 UTC, johnmeneghini commented on modules.d/95nvmf/nvmf-autoconnect.sh
>  if [ -f /etc/nvme/discovery.conf ] && [ $NVMF_HOSTNQN_OK ]; then
fixed

2023-04-21 15:17 UTC, johnmeneghini commented
> This must be merged with #5. Also, the `connect-all` logic must be discussed.
> 
> AFAICS, we have two options now:
> 
> 1. Just use `connect-all`, as suggested by @hreinecke, and don't bother about using NBFT or local configuration. That would simplify the dracut code substantially, and it would (sort of) minimize the risk that the root FS isn't found we donn't connect to the subsystem that contains it. It suffers from the issues mentioned above though.
> 2. Fix the existing logic to handle the various cases mentioned above.
> 
> Not surprisingly, I vote for 2. I'd like to base our upstream dracut PR on 2.), and have a discussion about the `connect-all` logic in the upstream PR. If upstream comes to the conclusion that the complexity of differentiating the various cases is unnecessary, we can still simplify the PR.

OK. let's go with option 2.  I will l make the appropriate changes and then rebase both  `timberland_final_v3` and `timberland_final_v3-mwilck` onto the the `timberland_final`

2023-04-22 03:05 UTC, johnmeneghini commented on modules.d/95nvmf/nvmf-autoconnect.sh
> +    /usr/sbin/nvme connect-all
I have fixed this problem and rebased this branch onto `timberland_final`

2023-04-22 03:06 UTC, johnmeneghini commented on modules.d/95nvmf/nvmf-autoconnect.sh
>  if [ -f /etc/nvme/discovery.conf ] && [ $NVMF_HOSTNQN_OK ]; then
I have fixed this problem and rebased this branch onto `timberland_final`

2023-04-25 15:51 UTC, johnmeneghini commented
This pull request has merged #7 and is now ready to be merged into timberland _final.

2023-04-27 13:57 UTC, mwilck approved these changes
My suggestions have been merged, thanks!

2023-04-27 16:40 UTC, mwilck commented
@johnmeneghini: I will rebase-merge this on the command line, because I strongly dislike github's rebase-and-merge behavior.

2023-04-27 16:54 UTC, mwilck requested changes
@johnmeneghini,

something went wrong here. In your merge-and-squash operation, you lost part of my commit 48508e5, and entirely removed 83a5260.

Please double-check.

2023-04-27 16:55 UTC, mwilck commented
Something went wrong merging #7 into this PR. I can't merge this into the timberland_final branch just yet.

2023-05-02 14:01 UTC, johnmeneghini commented
> @johnmeneghini,
> 
> something went wrong here. In your merge-and-squash operation, you lost part of my commit [48508e5](https://github.com/timberland-sig/dracut/commit/48508e55b46eb5a25b835dee2976c1d300a944ac), and entirely removed [83a5260](https://github.com/timberland-sig/dracut/commit/83a5260f685fa135df2e96c3b4157287f05b46f6).
> 
> Please double-check.

OK I will look at this.

2023-05-02 16:41 UTC, johnmeneghini commented
I've merged your pull request #8 into this branch and now the Commisery test is failing on your patch.  I have no idea why this is happening because all of the commit headers look correct to me.  The last time I encountered this error it was because one of the patches had a "signed-off-by" label.

I'm still not sure how I lost your change in the first place.  IIRC it was probably because of a problem like this. I hate software that thinks it knows what I want... from now I am going to merge all of my changes with a forced push.  That way I know the SHA will be added to the branch...

Please just squash this branch and merge it.  Note that you may need to use your branch from #8 for squashing and merging because Github has not added this patch to the branch for #6 yet.

2023-05-02 19:47 UTC, mwilck commented
Force-pushed this branch to 0aba896 just to get rid of the merge commit that commisery doesn't like.

2023-05-02 19:52 UTC, johnmeneghini commented
> Force-pushed this branch to [0aba896](https://github.com/timberland-sig/dracut/commit/0aba8963b54a15595b3e06356e085fa367a2a0f5) just to get rid of the merge commit that commisery doesn't like.

OK. if you are happy with this branch you should go a head and merge it.

2023-05-02 20:47 UTC, mwilck commented
Rebased and force-pushed again. No code changes. I just squashed the entire NBFT related code into a single commit, and rewrote the commit description.

Last (trivial) step will be rebase to current upstream HEAD.

@johnmeneghini, @charles-rose, please have a final look.

2023-05-02 22:16 UTC, johnmeneghini reviewed
This all looks good Martin.  Thanks for updating this.

2023-05-02 22:28 UTC, johnmeneghini commented
Why does this branch have merge conflicts?

I think you need to rebase everything here to the tip of the master branch.

2023-05-03 08:53 UTC, mwilck commented on modules.d/95nvmf/nvmf-autoconnect.sh
> +#!/bin/sh
It should have been one from day 1. Scripts that run during boot should be POSIX shell, not bash.

2023-05-03 09:06 UTC, mwilck commented
> Why does this branch have merge conflicts?

They are merge conflicts with the current `timberland_final` branch (where the old nvme-cli command line syntax was used), not with upstream. I just tried on the command line, and there are also merge conflicts between `timberland_final` and your `timberland_final_v4-johnm` branch, the same as here. They could be trivially resolved, but eventually we're going to force-push anyway, so I don't think this is an issue.

> I think you need to rebase everything here to the tip of the master branch.

With "master" you mean "upstream master"? That wouldn't make a difference, the merge conflicts with `timberland_final` would remain, as they're between the old and new timberland code.

2023-05-04 02:17 UTC, johnmeneghini commented
On 5/3/23 05:06, Martin Wilck wrote:
> With "master" you mean "upstream master"? That wouldn't make a difference, the merge conflicts with |timberland_final| would 
> remain, as they're between the old and new timberland code.

Yes, I mean I think we should rebase the upstream pull request `timberland_final` to the HEAD of the upstream master branch.

2023-05-04 13:56 UTC, mwilck commented
@johnmeneghini,  @charles-rose: You still didn't say anything about my rebase operation and the rewritten commit message.

2023-05-04 13:58 UTC, mwilck approved these changes
I was still listed as requesting changes… I obviously approve this PR now.

2023-05-04 14:01 UTC, mwilck commented
I'm going to "merge" this now by force-pushing this code to `timberland_final`.

2023-05-04 14:02 UTC, merged

2023-05-04 14:03 UTC, mwilck commented
With all changes from this branch now "merged" into `timberland_final`, we're good to close here.